workdir: /run/media/fabio/9a846308-6659-4a3e-b18f-58210fc0f88a1/hitac/benchmark

threads: 12

benchmark:
    repeat: 1

datasets:
    - sp_rdp_its.90
    - sp_rdp_its.95
    - sp_rdp_its.97
    - sp_rdp_its.99
    - sp_rdp_its.100

scripts:
    - fasta_utax2_to_blca.py
    - blca2tab.py
    - bbc_cutoff.py
    - spingo2tab.py
    - fasta.py
    - qiime2tax2tab.py
    - fasta_utax2_to_metaxa2.py
    - progress.py
    - utax2.py
    - sortdict.py
    - metaxa2tab.py
    - fasta_utax2qiime.py
    - fasta_utax2spingo.py
    - die.py
    - mothur_make_taxtrainfiles.py
    - qiimetax2tab.py
    - rdpc2tab3.py
    - motknn2utax2.py
    - taxbenchx.py
    - btop2tab.py
    - microclass.R
    - microclass2tab.py
    - fasta_utax2rdp.py

methods:
    - blca
    - btop
    - ct1
    - ct2
    - hitac_qiime
    - hitac_standalone
    - hitac_filter_qiime
    - hitac_filter_standalone
    - knn
    - ktop
    - metaxa2
    - microclass
    - nbc50
    - nbc80
    - q1
    - q2blast
    - q2sk
    - q2vs
    - rdp50
    - rdp80
    - sintax50
    - sintax80
    - spingo
    - top

ranks:
    - p  # phylum
    - c  # class
    - o  # order
    - f  # family
    - g  # genus
    - s  # species

containers:
    hitac_qiime: "docker://mirand863/hitac_qiime:2.1.0"
    hitac_standalone: "docker://mirand863/hitac_standalone:2.1.0"
    blca: "docker://mirand863/blca:2.3"
    btop: "docker://mirand863/btop:2.10.1"
    usearch: "docker://mirand863/usearch:11.0.667"
    knn: "docker://mirand863/knn:1.48"
    spingo: "docker://mirand863/spingo:1.3"
    rdp: "docker://mirand863/rdp:2.13"
    microclass: "docker://mirand863/microclass:1.2"
    metaxa2: "docker://mirand863/metaxa2:2.2.3"
    pandas: "docker://mirand863/pandas:1.4"
    qiime1: "docker://mirand863/qiime:1.9.1"
    qiime2: "docker://quay.io/qiime2/core:2023.2"
    python2: "docker://python:2.7-slim"

urls:
    train: "https://drive5.com/taxxi/benchmark/trainfa/{dataset}"
    test: "https://drive5.com/taxxi/benchmark/testfa/{dataset}"
    scripts: "https://raw.githubusercontent.com/mirand863/taxxi/master/benchmark/py/{script}"
    namecounts: "https://raw.githubusercontent.com/mirand863/taxxi/master/benchmark/namecounts/{dataset}"
