cluster: "sbatch -A renard -p {resources.partition} --cpus-per-task {resources.cpus} --mem={resources.mem_gb}G --gpus={resources.gpus} --time={resources.time} --constraint 'ARCH:X86'"
jobs: 6
default-resources: [cpus=1, gpus=0, mem_gb=1, time='5-00:00:00', partition=magic]
resources: [cpus=120, gpus=0, mem_gb=300]
use-conda: true
conda-frontend: mamba
restart-times: 24
keep-going: true
printshellcmds: true
reason: true
