stages:
  - version
  - build
  - test
  - deploy


bump-version:
  image: python:3.8.3-buster
  stage: version
  script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - pip install semver
    - python resources/gen-semver
  only:
    - master


build-test-image:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: $CI_REGISTRY/dacs-hpi/hitac/testimage:latest
    DOCKERFILE: tests/Dockerfile
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG --file $DOCKERFILE .
    - docker push $IMAGE_TAG
  only:
    changes:
      - tests/Dockerfile


test-functions:
  image: $CI_REGISTRY/dacs-hpi/hitac/testimage:latest
  stage: test
  script:
    - pytest -v


deploy-pypi:
  image: python:latest
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=$PYPI_TOKEN TWINE_USERNAME=__token__ python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
  only:
    - tags


deploy-docker:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    REPOSITORY: mirand863/hitac
    PUSHRM: https://github.com/christian-korneck/docker-pushrm/releases/download/v1.7.0/docker-pushrm_linux_amd64
    DOCKERFILE: deploy/Dockerfile
  before_script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-pushrm $PUSHRM
    - chmod +x $HOME/.docker/cli-plugins/docker-pushrm
  script:
    - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
    - docker build -t $REPOSITORY:$CI_COMMIT_TAG -t $REPOSITORY:latest --file $DOCKERFILE .
    - docker push $REPOSITORY --all-tags
    - docker pushrm $REPOSITORY
  only:
    - tags
