#!/bin/bash

name=$1

qfa=../testfa/$name
dbfa=../trainfa/$name

rawdir=../raw/hitac
mkdir -p $rawdir
raw=$rawdir/$name

preddir=../pred/hitac
mkdir -p $preddir
pred=../pred/hitac/$name

# Must be at same level as scripts/
tmpdir=../tmp_hitac.$$.$RANDOM
mkdir -p $tmpdir
cd $tmpdir

python2 ../py/fasta_utax2qiime.py $dbfa dbq.fa db-tax.txt

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

qiime tools import \
--input-path $qfa \
--output-path q-seqs.qza \
--type 'FeatureData[Sequence]'

qiime tools import \
--input-path dbq.fa \
--output-path db-seqs.qza \
--type 'FeatureData[Sequence]'

qiime tools import \
--type 'FeatureData[Taxonomy]' \
--input-format HeaderlessTSVTaxonomyFormat \
--input-path db-tax.txt \
--output-path db-tax.qza

qiime hitac classify \
--i-reference-reads db-seqs.qza \
--i-reference-taxonomy db-tax.qza \
--i-query q-seqs.qza \
--o-classification classifier_output.qza --verbose

qiime tools export \
--input-path classifier_output.qza \
--output-path output_dir

cp -v output_dir/taxonomy.tsv $raw

python2 ../py/qiime2tax2tab.py $raw > $pred
rm -rf $tmpdir
