cluster: "sbatch -A renard -p {resources.partition} --cpus-per-task {resources.cpus} --mem={resources.mem_kb}K --gpus={resources.gpus} --time={resources.time} --constraint 'ARCH:X86' --output='slurm-%j.out' --error='slurm-%j.err'"
jobs: 1
default-resources: [cpus=1, gpus=0, mem_kb=1000000, time='1-00:00:00', partition=magic]
resources: [cpus=288, gpus=6, mem_kb=480000000]
use-conda: true
conda-frontend: mamba
restart-times: 24
keep-going: true
printshellcmds: true
reason: true
