cluster: "sbatch -A renard -p {resources.partition} --cpus-per-task {resources.cpus} --mem={resources.mem_gb}G --gpus={resources.gpus} --time={resources.time} --constraint 'ARCH:X86' --output='slurm-%j.out' --error='slurm-%j.err'"
jobs: 24
default-resources: [cpus=1, gpus=0, mem_gb=1, time='1-00:00:00', partition=magic]
resources: [cpus=288, gpus=6, mem_gb=2048]
use-conda: true
conda-frontend: mamba
restart-times: 24
keep-going: true
printshellcmds: true
reason: true
