workdir: /home/fabio/Desktop/hitac/pre_trained

urls:
  unite: "https://files.plutof.ut.ee/public/orig/FB/78/FB78E30E44793FB02E5A4D3AE18EB4A6621A2FAEB7A4E94421B8F7B65D46CA4A.tgz"

slurm:
  memory_increments_gb: 10  # increment memory allocation if task fails
