workdir: /home/fabio/Desktop/hitac/pre_trained

urls:
  unite:
    fungi_refs: "https://s3.hpc.ut.ee/plutof-public/original/db1d6ddb-a35d-48c5-8b1a-ad9dd3310c6d.tgz"
    fungi_global: "https://s3.hpc.ut.ee/plutof-public/original/06daa092-e96a-48e7-9303-4402cc5c46c5.tgz"
    eukaryotes_refs: "https://s3.hpc.ut.ee/plutof-public/original/711a503c-589d-4138-a76f-6a8b89460ecf.tgz"
    eukaryotes_global: "https://s3.hpc.ut.ee/plutof-public/original/55665851-81f9-4704-8287-b5971abbf85c.tgz"

slurm:
  memory_increments_kb: 20000000  # increment memory allocation if task fails
