FROM quay.io/qiime2/core:2021.8

RUN pip install \
coverage==5.5 \
flake8==3.9.2 \
iniconfig==1.1.1 \
mccabe==0.6.1 \
packaging==21.0 \
pluggy==0.13.1 \
py==1.10.0 \
pycodestyle==2.7.0 \
pydocstyle==6.1.1 \
pyflakes==2.3.1 \
pyparsing==2.4.7 \
pytest==6.2.4 \
pytest-cov==2.12.1 \
pytest-flake8==1.0.7 \
pytest-pydocstyle==2.2.0 \
snowballstemmer==2.1.0 \
toml==0.10.2 \
black==21.11b1 \
hiclass==2.0.6 \
--quiet
