configfile: "config/config.yml"

workdir: config["workdir"]

include: "rules/download_unite.smk"

rule all:
    input:
        unite = expand(
            "data/unite/{dataset}.tgz",
            dataset=config["urls"]["unite"],
        )
