name: Publish Docker image

on: [pull_request]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mirand863/hitac
        run: |
          echo "TAG_NAME=$(git tag --sort=taggerdate | tail -1)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          file: deploy/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.TAG_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
