name: Test PR

on: [pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/qiime2/core:2023.2
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"
    - name: Test with pytest
      run: |
        flake8 hitac tests
        pydocstyle hitac
        pytest -v --cov=hitac --cov-fail-under=70 --cov-report html
        coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2

#  docker:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
##        container: [blca, btop, usearch, hitac, knn, spingo, rdp, microclass, pandas, metaxa2]
##       container: [hitac_qiime, hitac_standalone]
#       container: [r_base]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: mirand863/${{ matrix.container }}
#          tags: |
#            type=raw,value=4.3.2
#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          file: benchmark/dockerfiles/${{ matrix.container }}.dockerfile
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
