name: Test PR

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/qiime2/core:2023.2
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8==3.9.2
        python -m pip install pytest==6.2.4
        python -m pip install py==1.11.0
        python -m pip install pytest-flake8==1.0.7
        python -m pip install pydocstyle==6.1.1
        python -m pip install pytest-pydocstyle==2.2.0
        python -m pip install pytest-cov==2.12.1
        python -m pip install .
    - name: Test with pytest
      run: |
        pytest -v --flake8 --pydocstyle --cov=hitac --cov-fail-under=75 --cov-report html
        coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
