name: Test PR

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/qiime2/core:2023.2
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install flake8
        python -m pip install pydocstyle
        python -m pip install pytest-cov
        python -m pip install torch
        python -m pip install transformers
        python -m pip install .
    - name: Test with pytest
      run: |
        flake8 hitac tests
        pydocstyle hitac
        pytest -v --cov=hitac --cov-fail-under=70 --cov-report html
        coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
